#!/usr/bin/env python3
"""
Generates a real, standalone, indexable URL for every Art Radar post
(radar/<slug>/index.html) from content/posts.html and the archive page radar/index.html.
The sitemaps are written by tools/build_sitemap.py (python3 build.py runs it after this).

Run it after adding a new post block to content/posts.html (python3 build.py runs it
for you, together with build-site-pages.py and build-home.py). The only thing it
rewrites inside content/posts.html is each post's JSON-LD `url` / `mainEntityOfPage`
(fragment -> real URL). No visible "Permalink" link is added to posts: the site owner
removed those on 2026-07-02. The /radar/<slug>/ pages are the canonical post URLs.

index.html is generated by build-home.py and never carries posts; this script refuses
to run if it finds one there (site_chrome.guard_index).
"""
import glob
import html as H
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import site_chrome as sc
from site_chrome import SITE, T

OUT_DIR = 'radar'

sc.guard_index()
html, posts = sc.read_posts()
print(f"Found {len(posts)} posts")

# ---- 1. Rewrite JSON-LD url/mainEntityOfPage in content/posts.html to real permalinks ----
# Safe to re-run: posts already using the real permalink are left untouched.
new_html = html
for p in posts:
    frag_url = f"{SITE}/#{p['slug']}"
    real_url = f"{SITE}/radar/{p['slug']}/"
    old_json = p["json_text"]
    new_json = old_json.replace(
        f'"url": "{frag_url}"', f'"url": "{real_url}"'
    ).replace(
        f'"mainEntityOfPage": "{frag_url}"', f'"mainEntityOfPage": "{real_url}"'
    )
    if new_json != old_json:
        new_html = new_html.replace(old_json, new_json, 1)
        p["json_text"] = new_json
if new_html != html:
    open(sc.POSTS_FILE, "w", encoding="utf-8", newline="").write(new_html)
    print("content/posts.html updated (JSON-LD permalink URLs)")


# ---- 2. radar/<slug>/index.html for every post ----
TITLE_RE = re.compile(r'\s*<h2 class="post-title[^"]*"[^>]*>.*?</h2>', re.S)
NJ_WORDS = re.compile(r'Montclair|Bergen|librar|New Jersey|Tenafly|Closter|Demarest|Cresskill|Alpine|Englewood', re.I)


def h1_title(inner, p):
    """The post page is the post's own page, so its title is the page's one h1: the two
    <h2 class="post-title"> twins of the source become one <h1> holding both twins."""
    matches = list(TITLE_RE.finditer(inner))
    if not matches:
        return inner
    h1 = f'\n    <h1 class="post-title">{T(H.escape(p["title_en"]), H.escape(p["title_he"]))}</h1>'
    out = inner[:matches[0].start()] + h1
    prev_end = matches[0].end()
    for m in matches[1:]:
        out += inner[prev_end:m.start()]
        prev_end = m.end()
    return out + inner[prev_end:]


def about_new_jersey(p):
    text = p["headline"] + " " + re.sub(r"<[^>]+>", " ", p["article_inner"])
    return bool(NJ_WORDS.search(text))


def working_with_stav(p):
    """Under every post: one line on what Stav does and where, the two landing pages (the New
    Jersey one first when the post is about New Jersey), and the mailto."""
    nj = f'<a href="/art-curator-new-jersey/">{T("Art curator in New Jersey", "אוצרת אמנות בניו ג\'רזי")}</a>'
    ny = f'<a href="/art-curator-new-york/">{T("Art curator in New York", "אוצרת אמנות בניו יורק")}</a>'
    links = (nj + ny) if about_new_jersey(p) else (ny + nj)
    return f'''
<section class="section wrap tight">
  <div class="cta reveal" id="working-with-stav">
    <p class="eyebrow">{T('Working with Stav', 'עבודה עם סתיו')}</p>
    <h2 class="serif">{T('Art curator and advisor in Tenafly, New Jersey, for New York, Bergen County and Tel Aviv.', "אוצרת ויועצת אמנות בטנפליי, ניו ג'רזי, לניו יורק, למחוז ברגן ולתל אביב.")}</h2>
    <div class="readnext">{links}</div>
    <a class="btn" href="mailto:{sc.EMAIL}">{T('Write to Stav', 'כתבו לסתיו')}</a>
  </div>
</section>
'''


def render_post_page(p, all_posts):
    permalink = f"{SITE}/radar/{p['slug']}/"
    # Post pages live at /radar/<slug>/, so relative image paths copied from the
    # source would resolve to /radar/<slug>/images/... and 404. Make them root-relative.
    article_inner = p["article_inner"].replace('src="images/', 'src="/images/').replace('src="videos/', 'src="/videos/')
    article_inner = h1_title(article_inner, p)
    breadcrumb = {
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": [
            {"@type": "ListItem", "position": 1, "name": "THEODORA", "item": SITE + "/"},
            {"@type": "ListItem", "position": 2, "name": "Art Radar", "item": SITE + "/radar/"},
            {"@type": "ListItem", "position": 3, "name": p["headline"], "item": permalink},
        ],
    }
    others = [o for o in all_posts if o["slug"] != p["slug"]][:6]
    body = f'''
<header class="phead">
  <p class="eyebrow"><a href="/radar/">{T('Art Radar', 'ראדאר אמנות')}</a></p>
</header>

<main class="wrap">
  <article class="{p['article_class']} article" id="{p['slug']}">{article_inner}</article>
</main>
{working_with_stav(p)}
<section class="section wrap">
  <div class="head reveal">
    <div class="lead"><p class="eyebrow">{T('More from Art Radar', 'עוד מראדאר אמנות')}</p><h2 class="serif">{T('The art worth seeing, chosen by a curator.', 'האמנות ששווה לראות, בבחירת אוצרת.')}</h2></div>
    <a class="arrow" href="/radar/"><span class="ln"></span>{T('All posts', 'כל הפוסטים')}</a>
  </div>
  <div class="timeline">{sc.timeline(others, with_months=False)}
  </div>
</section>
'''
    return (sc.head(f"{p['headline']} · Art Radar · THEODORA", p['description'], permalink,
                    og_image=p['og_image'], og_type='article', lang='en',
                    ld=[p['json_text'], breadcrumb])
            + sc.body_open() + sc.nav() + body + sc.tail())


for p in posts:
    out_path = os.path.join(OUT_DIR, p["slug"], "index.html")
    sc.write(out_path, render_post_page(p, posts))
    print(f"  wrote {out_path}")


# ---- 3. radar/index.html: every post, in order ----
def render_radar_index(posts):
    n = len(posts)
    url = f"{SITE}/radar/"
    latest_img = posts[0]['img'] or '/images/home2/garden-villa.jpg'
    collection = {
        "@context": "https://schema.org", "@type": "CollectionPage",
        "name": "Art Radar, every post", "url": url, "inLanguage": ["he", "en"],
        "description": "Every Art Radar post in order: exhibitions, openings and museum events in New York, New Jersey and Tel Aviv, chosen by curator Stav Theodor-Kimhi.",
        "isPartOf": {"@id": SITE + "/#site"},
        "hasPart": [{"@type": "BlogPosting", "headline": p["headline"], "url": f"{SITE}/radar/{p['slug']}/", "datePublished": p["datePublished"]} for p in posts],
    }
    breadcrumb = {
        "@context": "https://schema.org", "@type": "BreadcrumbList",
        "itemListElement": [
            {"@type": "ListItem", "position": 1, "name": "THEODORA", "item": SITE + "/"},
            {"@type": "ListItem", "position": 2, "name": "Art Radar", "item": url},
        ],
    }
    body = f'''
<header class="phero" style="height: 62vh; min-height: 480px;">
  <img src="{latest_img}" alt="" fetchpriority="high">
  <div class="scrim"></div>
  <div class="title">
    <p class="eyebrow">{T('Art Radar', 'ראדאר אמנות')}</p>
    <h1 class="serif">{T(f'Every post, in order. {n} so far.', f'כל הפוסטים, לפי הסדר. {n} עד היום.')}</h1>
    <p class="cap">{T('The art worth seeing in New York, New Jersey and Tel Aviv, chosen by a curator. Written in Hebrew first, each with a full English translation.', "האמנות ששווה לראות בניו יורק, בניו ג'רזי ובתל אביב, בבחירת אוצרת. נכתב קודם בעברית, וכל פוסט עם תרגום מלא לאנגלית.")}</p>
  </div>
</header>

<section class="section wrap tight">
  <div class="head reveal">
    <div class="lead"><p class="eyebrow">{T('Get it first', 'קבלו את זה ראשונים')}</p><h2 class="serif">{T('The posts go to the WhatsApp group first.', 'הפוסטים מגיעים קודם לקבוצת הוואטסאפ.')}</h2></div>
    <a class="btn" href="{sc.WHATSAPP}" target="_blank" rel="noopener">{T('Join the WhatsApp Group', 'הצטרפו לקבוצת הוואטסאפ')}</a>
  </div>
  <div class="timeline" id="posts">{sc.timeline(posts, with_months=True)}
  </div>
</section>
'''
    return (sc.head('Art Radar, every post · THEODORA', collection['description'], url,
                    og_image=SITE + latest_img, lang='en', ld=[collection, breadcrumb])
            + sc.body_open() + sc.nav() + body + sc.tail())


sc.write(os.path.join(OUT_DIR, 'index.html'), render_radar_index(posts))
print("  wrote radar/index.html")
