#!/usr/bin/env python3
"""The chrome every generated page of stavtheodor.com shares.

One nav, one footer, one language switch, one mailto fallback panel, one GA tag, one
<head> builder, and the readers for the site's data files:

  content/posts.html   every Art Radar post (JSON-LD + <article> pairs, newest first)
  content/faq.json     the seven homepage questions (visible FAQ and FAQPage schema come from it)
  content/entity.json  the site-wide nodes (ProfessionalService, Person, WebSite) every page's graph opens with
  content/spaces.json  the before/after space pairs (images/spaces/), for before_after()

The generators import this module: build-home.py (index.html, the buyer variants of it from
content/variants/, whose footer and mail panel carry a mail subject, the /2/ redirect stubs),
build-post-pages.py (radar/<slug>/, radar/, sitemap.xml) and build-site-pages.py
(advisory, projects, partners, guide). The theme itself is css/theme.css.

Rules honored everywhere: every visible string has an English and a Hebrew twin behind
the global switch (localStorage radarLang); every page opens in English unless the
visitor chose Hebrew (site owner's decision, 2026-09-26), so <body class="lang-en"> is in
the markup and no hreflang tags are emitted; the mailto fallback ships on every page; the
business line (201) 351-8367 and no other number; one JSON-LD graph per page (page_graph);
no em or en dashes anywhere (write() runs the dash sanitizer on every page, 2026-09-29).
"""
import html as H
import json
import os
import re
from urllib.parse import quote

ROOT = os.path.dirname(os.path.abspath(__file__))
SITE = 'https://stavtheodor.com'
GA_ID = 'G-4300MN0Q97'
EMAIL = 'stav@stavtheodor.com'
WHATSAPP = 'https://chat.whatsapp.com/CapF9HczSoL4szwUKKtkq5'
INSTAGRAM = 'https://www.instagram.com/theodorafineart/'
# The business line (Ron's SEO brief, 2026-09-29, which replaces the 2026-07-02 rule of no phone at all):
# shown as (201) 351-8367, dialed as tel:+12013518367, in schema as +1-201-351-8367. It is the only number
# the site may carry; tools/check_site.py fails the build on any other (AGENTS.md content rule 6).
PHONE = '(201) 351-8367'
PHONE_TEL = 'tel:+12013518367'
PHONE_SCHEMA = '+1-201-351-8367'
YELP = 'https://www.yelp.com/biz/the-odora-tenafly'
# The contact form's endpoint (Ron's SEO brief, 2026-09-29, P1.1): the one build constant for it. The backend is Formspree
# (Ron's form, target stav@stavtheodor.com; set 2026-09-29, replacing the short lived Google Apps Script plan). Set, so the
# form, its progressive enhancement script and the GA4 generate_lead event appear on /contact/ and in the homepage's
# #contact; empty it and no form, no form script and no placeholder reaches any page.
FORM_ENDPOINT = 'https://formspree.io/f/xjyklwyb'
ORG_ID = SITE + '/#org'
STAV_ID = SITE + '/#stav'
POSTS_FILE = os.path.join(ROOT, 'content', 'posts.html')
FAQ_FILE = os.path.join(ROOT, 'content', 'faq.json')
ENTITY_FILE = os.path.join(ROOT, 'content', 'entity.json')
SPACES_FILE = os.path.join(ROOT, 'content', 'spaces.json')
THEME_CSS = '/css/theme.css'


def rel(*parts):
    return os.path.join(ROOT, *parts)


# ---------------------------------------------------------------- guards
def guard_index():
    """index.html is generated by build-home.py. A post pasted into it by hand would be
    wiped by the next build, so every build refuses to run while one is there."""
    p = rel('index.html')
    if os.path.exists(p) and '<article class="post' in open(p, encoding='utf-8').read():
        raise SystemExit(
            'STOP: index.html contains an Art Radar <article class="post ...">.\n'
            'Posts live in content/posts.html (see ADD-BLOG-POST-GUIDE.md). index.html is generated.\n'
            'Move the post block (its JSON-LD <script> + <article>) to the top of content/posts.html,\n'
            'restore index.html (git checkout index.html), then run python3 build.py again. Nothing was written.'
        )


# ---------------------------------------------------------------- small helpers
def strip_tags(s):
    return H.unescape(re.sub(r'\s+', ' ', re.sub(r'<[^>]+>', '', s or ''))).strip()


def first_sentence(s):
    s = strip_tags(s)
    m = re.match(r'(.+?[.!?])(\s|$)', s)
    return (m.group(1) if m else s).strip()


def T(en, he, tag='span', cls=''):
    """An English and a Hebrew twin. The site's switch shows one of them."""
    c = f' class="{cls}"' if cls else ''
    return f'<{tag}{c} data-l="en">{en}</{tag}><{tag}{c} data-l="he" dir="rtl">{he}</{tag}>'


def img_alt(en, he=''):
    """An image's alt: English in the markup (English opens first), and the Hebrew twin as data-alt-he,
    which LANG_JS swaps in while Hebrew is on and back when it is off (2026-09-29, Hebrew QA)."""
    a = f'alt="{H.escape(en or "", quote=True)}"'
    return a + (f' data-alt-he="{H.escape(he, quote=True)}"' if he else '')


# ---------------------------------------------------------------- head pieces
FAVICONS = '''<link rel="icon" type="image/svg+xml" href="/favicon.svg">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32.png">
<link rel="apple-touch-icon" href="/apple-touch-icon.png">'''

# The fonts are self-hosted in /fonts/ and declared at the top of css/theme.css (2026-09-26); only the
# two faces the first paint needs are preloaded. No third-party font request, no preconnect.
FONTS = '''<link rel="preload" as="font" type="font/woff2" href="/fonts/dm-serif-display-latin.woff2" crossorigin>
<link rel="preload" as="font" type="font/woff2" href="/fonts/plus-jakarta-sans-latin.woff2" crossorigin>'''

# Google's standard tag, the same snippet the museum pages carry (museum/tools/build_artist_pages.py).
# gtag.js loads async from <head>, so fast bounces are counted (2026-09-28, the site owner's request;
# replaces the 2026-09-26 load-event deferral).
GA_SNIPPET = f'''<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id={GA_ID}"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){{dataLayer.push(arguments);}}
  gtag('js', new Date());
  gtag('config', '{GA_ID}');
</script>'''

_entity_cache = None


def strip_private(node):
    """Keys that start with an underscore are editor notes (for example the Google Business
    Profile placeholder in content/entity.json) and never reach a page."""
    if isinstance(node, dict):
        return {k: strip_private(v) for k, v in node.items() if not k.startswith('_')}
    if isinstance(node, list):
        return [strip_private(v) for v in node]
    return node


def entity_nodes():
    """The site-wide nodes (ProfessionalService #org, Person #stav, WebSite #site), from content/entity.json,
    a fresh copy each call."""
    global _entity_cache
    if _entity_cache is None:
        _entity_cache = json.dumps(strip_private(json.load(open(ENTITY_FILE, encoding='utf-8')))['@graph'], ensure_ascii=False)
    return json.loads(_entity_cache)


# Keys whose value names an agent. A copy of THEODORA or of Stav there becomes a bare @id reference, so each page
# defines the business and the person once (Ron's SEO brief, 2026-09-29, P0.4 rule 2).
REF_KEYS = ('provider', 'publisher', 'author', 'creator', 'founder', 'worksFor', 'brand', 'seller', 'organizer')


def _ref(v):
    if isinstance(v, list):
        return [_ref(x) for x in v]
    if not isinstance(v, dict):
        return v
    vid, name = v.get('@id'), str(v.get('name', ''))
    if vid == ORG_ID or (not vid and name == 'THEODORA'):
        return {'@id': ORG_ID}
    if vid == STAV_ID or (not vid and name.startswith('Stav Theodor')):
        return {'@id': STAV_ID}
    return v


def _tidy(node):
    """A page node for the one graph: no nested @context, THEODORA and Stav by @id only."""
    if isinstance(node, dict):
        return {k: _tidy(_ref(v) if k in REF_KEYS else v) for k, v in node.items() if k != '@context'}
    if isinstance(node, list):
        return [_tidy(v) for v in node]
    return node


def page_graph(ld=()):
    """Exactly one JSON-LD graph per page: the site-wide nodes first, then the page's own nodes
    (BreadcrumbList, Service, FAQPage, BlogPosting, CollectionPage...). A block is a dict, a JSON string
    (an Art Radar post's own block from content/posts.html) or a dict with an @graph."""
    nodes = entity_nodes()
    for b in ld:
        d = json.loads(b) if isinstance(b, str) else b
        items = d['@graph'] if isinstance(d, dict) and '@graph' in d else d if isinstance(d, list) else [d]
        nodes += [_tidy(n) for n in items]
    ids = [n['@id'] for n in nodes if isinstance(n, dict) and n.get('@id')]
    dup = sorted({i for i in ids if ids.count(i) > 1})
    if dup:
        raise SystemExit(f'page graph: {dup} defined twice; reference the site-wide node by @id instead')
    return {'@context': 'https://schema.org', '@graph': nodes}


def load_faq():
    faq = json.load(open(FAQ_FILE, encoding='utf-8'))
    for q in faq:
        for k in ('q_en', 'a_en', 'q_he', 'a_he'):
            assert q.get(k), f'faq.json: item missing {k}'
    return faq


def faq_schema(faq):
    return {
        '@context': 'https://schema.org',
        '@type': 'FAQPage',
        'mainEntity': [{'@type': 'Question', 'name': q['q_en'],
                        'acceptedAnswer': {'@type': 'Answer', 'text': q['a_en']}} for q in faq],
    }


def faq_details(faq, first_open=True):
    """The visible questions, the same text as the FAQPage schema, word for word."""
    return ''.join(f'''
      <details class="qa"{' open' if (i == 0 and first_open) else ''}>
        <summary><h3 class="serif">{T(H.escape(q["q_en"]), H.escape(q["q_he"]))}</h3><span class="plus" aria-hidden="true"></span></summary>
        <p class="body">{T(H.escape(q["a_en"]), H.escape(q["a_he"]))}</p>
      </details>''' for i, q in enumerate(faq))


def ld_script(block):
    text = block if isinstance(block, str) else json.dumps(block, ensure_ascii=False, indent=2)
    return f'<script type="application/ld+json">\n{text}\n</script>'


def head(title, desc, url, og_image=None, og_type='website', lang='en', ld=(), noindex=False,
         og_title=None, og_desc=None, og_card_dims=False, og_image_alt=None, extra=''):
    """Everything from <!DOCTYPE> to </head>. Canonical, Open Graph, Twitter, favicons,
    fonts, the theme, one JSON-LD graph (the site-wide nodes, then the page's ld blocks) and GA. No hreflang:
    both languages live at the same URL and English is the default, so the tags would
    only point every language at itself (dropped 2026-09-26)."""
    og_image = og_image or SITE + '/og-image.jpg'
    og_title = og_title or title
    og_desc = og_desc or desc
    dims = ''
    if og_card_dims:
        dims = '\n<meta property="og:image:width" content="1200">\n<meta property="og:image:height" content="630">'
    if og_image_alt:
        dims += f'\n<meta property="og:image:alt" content="{H.escape(og_image_alt, quote=True)}">'
    robots = '\n<meta name="robots" content="noindex">' if noindex else ''
    ld_html = ('<!-- Structured data: one graph, the site-wide nodes first (content/entity.json), then this page\'s -->\n'
               + ld_script(page_graph(ld)))
    return f'''<!DOCTYPE html>
<html lang="{lang}" data-default-lang="{lang}">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover">
<title>{H.escape(title)}</title>{robots}
<meta name="description" content="{H.escape(desc, quote=True)}">
<meta property="og:title" content="{H.escape(og_title, quote=True)}">
<meta property="og:description" content="{H.escape(og_desc, quote=True)}">
<meta property="og:type" content="{og_type}">
<meta property="og:url" content="{url}">
<meta property="og:image" content="{og_image}">{dims}
<meta property="og:site_name" content="THEODORA">
<meta property="og:locale" content="en_US">
<meta property="og:locale:alternate" content="he_IL">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="{H.escape(og_title, quote=True)}">
<meta name="twitter:description" content="{H.escape(og_desc, quote=True)}">
<meta name="twitter:image" content="{og_image}">
<link rel="canonical" href="{url}">
{FAVICONS}
{FONTS}
<link rel="stylesheet" href="{THEME_CSS}">
{extra}{ld_html}

{GA_SNIPPET}
</head>
'''


# ---------------------------------------------------------------- body pieces
LANG_BOOT = '''<script>
/* Resolve the language before anything paints. English is the default on every page
   (it is already on <body> and <html> in the markup, so crawlers and no-JS readers get
   English without this script). A choice the visitor made on any page, stored as
   radarLang, wins everywhere. No browser-language guessing. */
(function () {
  document.documentElement.classList.add('js');
  var lang = 'en';
  try { var s = localStorage.getItem('radarLang'); if (s === 'he' || s === 'en') { lang = s; } } catch (e) {}
  document.body.classList.toggle('lang-en', lang === 'en');
  document.body.classList.toggle('lang-he', lang === 'he');
  document.documentElement.lang = lang;
})();
</script>'''

# Ron's SEO brief, 2026-09-29: For business (P1.5) replaces the Museum item (P1.6: no main page links the museum; its
# pages stay live and indexed), and Contact goes to the real /contact/ page (P1.1). For business points at the
# homepage's "Who I work with" section until the commercial hub /corporate-art-consulting/ ships (P2.1).
NAV_ITEMS = [
    ('#about', 'About', 'אודות'),
    ('/projects/', 'Projects', 'פרויקטים'),
    ('#advisory', 'Advisory', 'ייעוץ'),
    ('#industries', 'For business', 'לעסקים'),
    ('/radar/', 'Art Radar', 'ראדאר אמנות'),
    ('#faq', 'Questions', 'שאלות'),
    ('/contact/', 'Contact', 'יצירת קשר'),
]
# Who I work with (Ron's SEO brief, 2026-09-29, P1.5): the seven pages for one kind of client each, in every footer and
# on the projects hub. Interior designers is /for-designers/ since /designers/ was merged into it (it redirects there).
WHO_I_WORK_WITH = [
    ('/for-designers/', 'Interior designers', 'מעצבי פנים'),
    ('/law-firms/', 'Law firms', 'משרדי עורכי דין'),
    ('/investment-firms/', 'Investment firms', 'חברות השקעה'),
    ('/wealth-managers/', 'Wealth managers', 'מנהלי הון'),
    ('/medical-practices/', 'Medical practices', 'מרפאות'),
    ('/restaurants/', 'Restaurants', 'מסעדות'),
    ('/hotels/', 'Boutique hotels', 'מלונות בוטיק'),
]
# Section links that have a page of their own: on the homepage they stay in-page, on every
# other page they go to that page instead of scrolling the homepage (2026-09-26).
SUBPAGE_FOR = {'#advisory': '/advisory/', '#about': '/about/'}  # /about/: a real page since 2026-09-29


def _link(href, home):
    """Section links stay in-page on the homepage. Elsewhere they go to their own page when
    one exists (Advisory), otherwise to the homepage section, except Contact: every page's
    footer carries id="contact"."""
    if href.startswith('#') and not home and href != '#contact':
        return SUBPAGE_FOR.get(href, '/' + href)
    return href


def nav_call():
    """Click to call at the right of the nav, before the language switch (2026-09-29). On a narrow screen the
    number gives way to the label Call (css/theme.css, .nav-call); the aria-label always reads the number."""
    return (f'<a class="nav-call" href="{PHONE_TEL}" data-loc="header" aria-label="Call THEODORA at {PHONE}">'
            f'<span class="num">{PHONE}</span><span class="short">{T("Call", "התקשרו")}</span></a>')


def phone_link(loc='cta'):
    """The number as a contact line under an email link or a Write to Stav button."""
    return f'<a class="arrow tel" href="{PHONE_TEL}" data-loc="{loc}"><span class="ln"></span>{PHONE}</a>'


def nav(home=False, own=None, sub=None):
    """own: section links a homepage-shaped page sends to their own page because it lacks the section
    (a buyer variant has no #museum: {'#museum': '/museum/'}, 2026-09-28).
    sub: an (en, he) pair, the small orientation line under the wordmark ("for hotels"), buyer variants only
    (Ron, 2026-09-29). It sits inside the wordmark so it lines up with it and stacks above the WebGL canvas;
    WM_SUB_JS shows it between the first fold and the black intro block."""
    own = own or {}
    links = ''.join(f'<a href="{own.get(h) or _link(h, home)}">{T(en, he)}</a>' for h, en, he in NAV_ITEMS)
    wm_sub = f'<span class="wm-sub" aria-hidden="true">{T(H.escape(sub[0]), H.escape(sub[1]))}</span>' if sub else ''
    return f'''<nav class="nav" aria-label="Main">
  <a class="wordmark" href="{'#hero' if home else '/'}">THEODORA{wm_sub}</a>
  <div class="right">
    <div class="links" id="links">{links}</div>
    {nav_call()}
    <div class="lang-switch" role="group" aria-label="Choose language / בחירת שפה">
      <button type="button" data-lang="he" aria-pressed="false">עברית</button>
      <button type="button" data-lang="en" aria-pressed="false">English</button>
    </div>
    <button type="button" class="menu-btn" id="menu-btn" aria-controls="links" aria-expanded="false">{T('Menu', 'תפריט')}</button>
  </div>
</nav>'''


def mail_href(subject=''):
    """The mailto link, with the subject line a buyer variant pre-fills (percent-encoded)."""
    return f'mailto:{EMAIL}' + (f'?subject={quote(subject, safe="")}' if subject else '')


FOOTER_CTA = ('Send me one photo of the wall and a line about the space. I’ll tell you what I see.',
              'שלחו לי תמונה אחת של הקיר ושורה על החלל. אספר לכם מה אני רואה.')


def nap(mail=None):
    """Name, place and phone, the same on every page (Ron's SEO brief, 2026-09-29): no street address, no map.
    mail: the mailto href (a buyer variant's carries its subject)."""
    mail = mail or mail_href()
    return f'''<address class="nap">
  <span data-l="en">THEODORA · Stav Theodor, art advisor and consultant</span><span data-l="he" lang="he" dir="rtl">THEODORA · סתיו תאודור, יועצת אמנות</span><br>
  <span data-l="en">Tenafly, New Jersey 07670 · Serving Tenafly, Bergen County, New Jersey and New York City, with projects in Tel Aviv</span><span data-l="he" lang="he" dir="rtl">טנפליי, ניו ג'רזי 07670 · משרתת את טנפליי, מחוז ברגן, ניו ג'רזי וניו יורק, עם פרויקטים בתל אביב</span><br>
  <a href="{PHONE_TEL}" data-loc="footer">{PHONE}</a> · <a href="{mail}" data-loc="footer">{EMAIL}</a>
</address>'''


def footer(home=False, cta=None, subject='', form=False):
    """cta: a plain-text (en, he) pair that replaces the closing line (a buyer variant's);
    subject: the mail subject both mailto links carry; form: the contact form under the phone line (the homepage's
    #contact, and only once FORM_ENDPOINT is set). The defaults are every page's footer.
    The link columns (Ron's SEO brief, 2026-09-29, P1.5 and P1.6): the site's main pages (the Tenafly and Bergen County
    pages first since Batch 3, P1.2 and P1.3), then Who I work with, the
    seven pages for one kind of client each; no link to the museum (its pages stay live and indexed)."""
    L = lambda h: _link(h, home)
    cta_en, cta_he = (H.escape(cta[0]), H.escape(cta[1])) if cta else FOOTER_CTA
    href = mail_href(subject)
    who = ''.join(f'<a href="{u}">{T(en, he)}</a>' for u, en, he in WHO_I_WORK_WITH)
    form_html = ('\n    ' + contact_form('/')) if form and FORM_ENDPOINT else ''
    return f'''<footer class="foot" id="contact">
  <div class="left">
    <p class="eyebrow">{T('Contact', 'יצירת קשר')}</p>
    <h2 class="serif">{T(cta_en, cta_he)}</h2>
    <a class="arrow" href="{href}"><span class="ln"></span>{T('Write to Stav', 'כתבו לסתיו')}</a>
    <a class="arrow" href="{href}" style="text-transform: none; letter-spacing: 0.02em;"><span class="ln"></span>{EMAIL}</a>
    {phone_link('cta')}{form_html}
    <div class="wordmark" style="margin-top: 40px;">THEODORA</div>
    {nap(href)}
  </div>
  <div class="cols2">
    <div>
      <a href="/art-consultant-tenafly-nj/">{T('Art consultant in Tenafly', 'יועצת אמנות בטנפליי')}</a><a href="/art-advisor-bergen-county/">{T('Art advisor in Bergen County', 'יועצת אמנות במחוז ברגן')}</a><a href="/art-curator-new-jersey/">{T('Art consultant in New Jersey', "יועצת אמנות בניו ג'רזי")}</a><a href="/art-curator-new-york/">{T('Art advisor in New York', 'יועצת אמנות בניו יורק')}</a><a href="/advisory/">{T('Art advisory', 'ייעוץ אמנות')}</a><a href="/projects/">{T('Projects', 'פרויקטים')}</a><a href="/radar/">{T('Art Radar', 'ראדאר אמנות')}</a><a href="{L('#faq')}">{T('Questions', 'שאלות')}</a><a href="/about/">{T('About', 'אודות')}</a><a href="/contact/">{T('Contact', 'יצירת קשר')}</a><a href="{WHATSAPP}" target="_blank" rel="noopener">{T('Art Radar on WhatsApp', 'ראדאר אמנות בוואטסאפ')}</a><a href="{INSTAGRAM}" target="_blank" rel="noopener">{T('Instagram', 'אינסטגרם')}</a>
    </div>
    <div class="who">
      <p class="eyebrow">{T('Who I work with', 'עם מי אני עובדת')}</p>{who}
    </div>
    <p class="eyebrow copy">{T('Tenafly, New Jersey · © 2026 THEODORA', "טנפליי, ניו ג'רזי · © 2026 THEODORA")}</p>
  </div>
</footer>'''


def contact_form(path='/', h='h3'):
    """The contact form (Ron's SEO brief, 2026-09-29, P1.1), or '' while FORM_ENDPOINT is empty. Formspree takes a plain
    HTML POST: without JavaScript the form posts and Formspree shows its own thank-you page; form_js() sends it with
    fetch instead. _subject names the mail Formspree sends to Stav, _gotcha is Formspree's
    honeypot, page carries the page's path (path, written here so it survives without JavaScript; form_js() refreshes it). The select's options carry their
    Hebrew in data-he (an option cannot hold the twin spans); form_js() swaps the visible text with the language, the
    submitted value stays English. The free plan takes no files, so the note asks for the photo by email.
    The thank-you card (2026-09-29) and the error line are in the markup, hidden, both languages as twins: the box
    (.contact-box, aria-live) stacks the form and the card in one grid cell, so the card replaces the form in place and
    the page does not move. h: the card's heading level (h3 under the footer's h2, h2 on /contact/ under its h1)."""
    if not FORM_ENDPOINT:
        return ''
    L = lambda en, he: T(en, he)
    opts = ''.join(f'<option value="{H.escape(en, quote=True)}" data-en="{H.escape(en, quote=True)}" data-he="{he}">{H.escape(en)}</option>'
                   for en, he in CLIENT_TYPES)
    mail = mail_href()
    email = f'<bdi class="ty-addr">{EMAIL}</bdi>'
    # The check is drawn by CSS (stroke-dashoffset); the dash lengths are the circle's and the tick's own lengths.
    check = ('<svg class="ty-check" viewBox="0 0 52 52" width="44" height="44" aria-hidden="true" focusable="false">'
             '<circle cx="26" cy="26" r="24"/><path d="M15 27l7 7 15-16"/></svg>')
    # Each language's name slot: filled by form_js() with the first word of the name field; the comma hides with it.
    name = '<span class="ty-named" hidden>, <bdi class="ty-name"></bdi></span>'
    return f'''<div class="contact-box" aria-live="polite">
    <form class="contact-form" action="{H.escape(FORM_ENDPOINT, quote=True)}" method="POST" data-loc="form">
      <input type="hidden" name="_subject" value="New inquiry from stavtheodor.com">
      <input type="text" name="_gotcha" tabindex="-1" autocomplete="off" style="position:absolute;left:-9999px" aria-hidden="true">
      <label>{L('Your name', 'השם שלכם')} <input type="text" name="name" autocomplete="name" required></label>
      <label>{L('Email', 'אימייל')} <input type="email" name="email" autocomplete="email" required></label>
      <label>{L('Phone (optional)', 'טלפון (לא חובה)')} <input type="tel" name="phone" autocomplete="tel"></label>
      <label>{L('I am a', 'מי אתם')} <select name="client_type">{opts}</select></label>
      <label>{L('Tell me about your space', 'ספרו לי על החלל שלכם')} <textarea name="message" rows="5" required></textarea></label>
      <input type="hidden" name="page" value="{H.escape(path, quote=True)}">
      <button type="submit">{L('Send', 'שליחה')}</button>
      <p class="form-note">{L('I reply by email. If you have a photo of the wall, reply to my email with it.', 'אני עונה במייל. אם יש לכם תמונה של הקיר, שלחו אותה בתשובה למייל שלי.')}</p>
      <p class="form-error" hidden><span data-l="en">Your message did not go through. Please write to <a href="{mail}" dir="ltr">{EMAIL}</a> or call <a href="{PHONE_TEL}" data-loc="form" dir="ltr">{PHONE}</a>.</span><span data-l="he" dir="rtl">ההודעה לא נשלחה. כתבו ל-<a href="{mail}" dir="ltr">{EMAIL}</a> או התקשרו ל-<a href="{PHONE_TEL}" data-loc="form" dir="ltr">{PHONE}</a>.</span></p>
    </form>
    <div class="form-thanks" hidden>
      {check}
      <{h} class="serif ty-head" tabindex="-1"><span data-l="en">Thank you{name}.</span><span data-l="he" dir="rtl">תודה{name}.</span></{h}>
      <p class="ty-next"><span data-l="en">Stav reads every message herself and replies personally from {email}.</span><span data-l="he" dir="rtl">סתיו קוראת כל הודעה בעצמה ועונה לכם אישית מהכתובת {email}.</span></p>
      <p class="ty-spam"><span data-l="en">If you do not hear back, check your spam folder or <a class="ty-link" href="{mail}">write directly</a>.</span><span data-l="he" dir="rtl">אם לא קיבלתם תשובה, בדקו את תיקיית הספאם או <a class="ty-link" href="{mail}">כתבו לה ישירות</a>.</span></p>
      <div class="ty-wait">
        <p class="eyebrow">{L('While you wait', 'בינתיים')}</p>
        <div class="ty-links">
          <a class="arrow" href="/projects/"><span class="ln"></span>{L('See the projects', 'לפרויקטים')}</a>
          <a class="arrow" href="/radar/"><span class="ln"></span>{L('Read Art Radar', 'לראדאר אמנות')}</a>
          <a class="arrow" href="{WHATSAPP}" target="_blank" rel="noopener"><span class="ln"></span>{L('Art Radar on WhatsApp', 'ראדאר אמנות בוואטסאפ')}</a>
        </div>
      </div>
    </div>
    </div>'''


# The form's "I am a" choices (value and English label, Hebrew label), in Ron's order.
CLIENT_TYPES = [
    ('Homeowner', 'בעלי בית'),
    ('Interior designer or architect', 'מעצבי פנים או אדריכלים'),
    ('Business or hospitality', 'עסק או אירוח'),
    ('Other', 'אחר'),
]


def form_js():
    """The form's progressive enhancement (inline, no library), or '' while FORM_ENDPOINT is empty. It posts FormData
    with fetch and Accept: application/json, a normal CORS request Formspree answers with JSON. On r.ok it fills the
    first word of the name into the thank-you card, fades the form out and the card in, in the same place (the box keeps
    its height, so nothing below moves), moves focus to the card's heading (and, only when the heading is out of view, glides
    it into view, through the homepage's Lenis when present) and sends GA4 generate_lead with the form id
    and the page path only (never the name, email, phone or message). On any other answer or a network error the form
    stays and its error line shows the email and the phone. It also keeps the select's visible text in the page's
    language (the body's lang-he class)."""
    if not FORM_ENDPOINT:
        return ''
    return '''<script>
document.querySelectorAll('form.contact-form').forEach(function (f) {
  var box = f.closest('.contact-box');
  var card = box && box.querySelector('.form-thanks');
  var err = f.querySelector('.form-error');
  var btn = f.querySelector('button[type=submit]');
  var he = function () { return document.body.classList.contains('lang-he'); };
  var opts = function () {
    var l = he() ? 'he' : 'en';
    f.querySelectorAll('option[data-he]').forEach(function (o) { o.textContent = o.getAttribute('data-' + l); });
  };
  opts();
  if (window.MutationObserver) { new MutationObserver(opts).observe(document.body, { attributes: true, attributeFilter: ['class'] }); }
  f.querySelector('[name=page]').value = location.pathname;
  function thanks(first) {
    card.querySelectorAll('.ty-name').forEach(function (s) { s.textContent = first; });
    card.querySelectorAll('.ty-named').forEach(function (s) { s.hidden = !first; });
    card.hidden = false;
    void card.offsetWidth;
    box.classList.add('sent');
    f.setAttribute('aria-hidden', 'true');
    var head = card.querySelector('.ty-head');
    try { head.focus({ preventScroll: true }); } catch (e) { head.focus(); }
    var r = card.getBoundingClientRect();
    if (r.top < 80 || r.top > (window.innerHeight || 0) - 120) {
      var still = window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches;
      var lenis = window.__theodoraLenis;
      if (lenis) { lenis.scrollTo(card, { offset: -120, immediate: still }); }
      else { card.scrollIntoView({ block: 'start', behavior: still ? 'auto' : 'smooth' }); }
    }
  }
  f.addEventListener('submit', function (e) {
    e.preventDefault();
    if (f.classList.contains('sending')) { return; }
    f.classList.add('sending');
    btn.setAttribute('aria-disabled', 'true');
    err.hidden = true;
    var first = (f.querySelector('[name=name]').value || '').trim().split(/\\s+/)[0] || '';
    if (first) { first = first.charAt(0).toUpperCase() + first.slice(1); }
    fetch(f.action, { method: 'POST', body: new FormData(f), headers: { Accept: 'application/json' } })
      .then(function (r) {
        if (!r.ok) { throw new Error(r.status); }
        f.reset();
        f.querySelector('[name=page]').value = location.pathname;
        if (card) { thanks(first); }
        if (window.gtag) { gtag('event', 'generate_lead', { form_id: 'contact', page_path: location.pathname }); }
      })
      .catch(function () {
        f.classList.remove('sending');
        btn.removeAttribute('aria-disabled');
        err.hidden = false;
      });
  });
});
</script>'''


# A buyer variant's mail subject survives the fallback panel. LANG_JS (inlined in index.html, left
# untouched) rebuilds the panel's three links from the bare address every time it opens the panel,
# so this puts the subject back each time the panel gains the class "open". Only pages with a
# subject carry it (2026-09-27).
SUBJECT_JS = '''<script>
(function () {
  var panel = document.getElementById('mail-fallback');
  var subject = panel ? panel.getAttribute('data-subject') : '';
  if (!subject || !window.MutationObserver) { return; }
  var su = encodeURIComponent(subject);
  new MutationObserver(function () {
    if (!panel.classList.contains('open')) { return; }
    var addrEl = document.getElementById('mail-fallback-addr');
    var addr = (addrEl.textContent || '').trim();
    var to = encodeURIComponent(addr);
    addrEl.setAttribute('href', 'mailto:' + addr + '?subject=' + su);
    document.getElementById('mail-fallback-gmail').setAttribute('href', 'https://mail.google.com/mail/?view=cm&fs=1&to=' + to + '&su=' + su);
    document.getElementById('mail-fallback-outlook').setAttribute('href', 'https://outlook.live.com/mail/0/deeplink/compose?to=' + to + '&subject=' + su);
  }).observe(panel, { attributes: true, attributeFilter: ['class'] });
})();
</script>'''


def mail_ui(subject=''):
    """The mailto fallback panel (AGENTS.md content rule 8). With a subject (a buyer variant) the
    panel carries it as data-subject, its three links carry it, and SUBJECT_JS follows the panel.
    Without one it is the panel every page ships (MAIL_UI)."""
    q = quote(subject, safe='')
    data = f' data-subject="{H.escape(subject, quote=True)}"' if subject else ''
    addr_q = f'?subject={q}' if subject else ''
    gmail_q = f'&amp;su={q}' if subject else ''
    outlook_q = f'&amp;subject={q}' if subject else ''
    return f'''<div class="mail-fallback" id="mail-fallback" role="dialog" aria-modal="true" aria-labelledby="mail-fallback-title"{data}>
  <div class="card">
    <h3 id="mail-fallback-title" class="serif"><span data-l="en">Write to Stav</span><span data-l="he" dir="rtl">כתבו לסתיו</span></h3>
    <p><span data-l="en">This browser has no email app set up, so nothing opened. Copy the address, or open it in your webmail.</span><span data-l="he" dir="rtl">בדפדפן הזה לא מוגדרת תוכנת דואר, ולכן לא נפתח כלום. העתיקו את הכתובת, או פתחו אותה בדואר האינטרנטי שלכם.</span></p>
    <a class="addr" id="mail-fallback-addr" href="mailto:{EMAIL}{addr_q}">{EMAIL}</a>
    <div class="row">
      <button type="button" id="mail-fallback-copy"><span data-l="en">Copy</span><span data-l="he" dir="rtl">העתקה</span></button>
      <a class="solid" id="mail-fallback-gmail" href="https://mail.google.com/mail/?view=cm&amp;fs=1&amp;to={EMAIL}{gmail_q}" target="_blank" rel="noopener">Gmail</a>
      <a id="mail-fallback-outlook" href="https://outlook.live.com/mail/0/deeplink/compose?to={EMAIL}{outlook_q}" target="_blank" rel="noopener">Outlook</a>
    </div>
    <button type="button" class="close"><span data-l="en">Close</span><span data-l="he" dir="rtl">סגירה</span></button>
  </div>
</div>''' + ('\n' + SUBJECT_JS if subject else '')


MAIL_UI = mail_ui()

LANG_JS = '''<script>
(function () {
  var KEY = 'radarLang';

  function apply(lang) {
    document.body.classList.toggle('lang-en', lang === 'en');
    document.body.classList.toggle('lang-he', lang === 'he');
    document.documentElement.lang = lang;
    /* An image with a Hebrew alt (data-alt-he, site_chrome.img_alt) reads it while Hebrew is on;
       the English alt the markup carries is kept in data-alt-en and comes back with English. */
    document.querySelectorAll('img[data-alt-he]').forEach(function (im) {
      if (!im.hasAttribute('data-alt-en')) { im.setAttribute('data-alt-en', im.getAttribute('alt') || ''); }
      im.setAttribute('alt', im.getAttribute(lang === 'he' ? 'data-alt-he' : 'data-alt-en'));
    });
    document.querySelectorAll('.lang-switch button').forEach(function (b) {
      var on = b.getAttribute('data-lang') === lang;
      b.classList.toggle('active', on);
      b.setAttribute('aria-pressed', on ? 'true' : 'false');
    });
  }

  apply(document.body.classList.contains('lang-he') ? 'he' : 'en');

  document.querySelectorAll('.lang-switch button').forEach(function (b) {
    b.addEventListener('click', function () {
      var lang = b.getAttribute('data-lang');
      try { localStorage.setItem(KEY, lang); } catch (e) {}
      apply(lang);
    });
  });

  /* A mailto: link does nothing at all in a browser with no mail handler registered,
     which is why the Write to Stav button felt dead. Keep the mailto (it is correct
     and works on phones and with a real mail client), and if the click was swallowed,
     offer the address, a copy button and webmail compose links instead. */
  var panel = document.getElementById('mail-fallback');
  if (!panel) { return; }
  var addrEl = document.getElementById('mail-fallback-addr');
  var gmail = document.getElementById('mail-fallback-gmail');
  var outlook = document.getElementById('mail-fallback-outlook');
  var copyBtn = document.getElementById('mail-fallback-copy');

  function closePanel() { panel.classList.remove('open'); }

  function openPanel(addr) {
    addrEl.textContent = addr;
    addrEl.setAttribute('href', 'mailto:' + addr);
    gmail.setAttribute('href', 'https://mail.google.com/mail/?view=cm&fs=1&to=' + encodeURIComponent(addr));
    outlook.setAttribute('href', 'https://outlook.live.com/mail/0/deeplink/compose?to=' + encodeURIComponent(addr));
    panel.classList.add('open');
  }

  panel.addEventListener('click', function (e) {
    if (e.target === panel || e.target.classList.contains('close') || (e.target.parentNode && e.target.parentNode.classList && e.target.parentNode.classList.contains('close'))) {
      closePanel();
    }
  });
  document.addEventListener('keydown', function (e) {
    if (e.key === 'Escape') { closePanel(); }
  });
  copyBtn.addEventListener('click', function () {
    var addr = addrEl.textContent;
    var done = function () {
      var spans = copyBtn.querySelectorAll('span');
      var was = [];
      spans.forEach(function (s, i) { was[i] = s.textContent; });
      spans.forEach(function (s) { s.textContent = s.getAttribute('data-l') === 'he' ? 'הועתק' : 'Copied'; });
      setTimeout(function () { spans.forEach(function (s, i) { s.textContent = was[i]; }); }, 1600);
    };
    if (navigator.clipboard && navigator.clipboard.writeText) {
      navigator.clipboard.writeText(addr).then(done, function () {});
    } else {
      var t = document.createElement('textarea');
      t.value = addr; document.body.appendChild(t); t.select();
      try { document.execCommand('copy'); done(); } catch (e) {}
      document.body.removeChild(t);
    }
  });

  document.addEventListener('click', function (e) {
    var a = e.target && e.target.closest ? e.target.closest('a[href^="mailto:"]') : null;
    if (!a || a === addrEl) { return; }
    var addr = a.getAttribute('href').slice(7).split('?')[0];
    var handled = false;
    function mark() { handled = true; }
    window.addEventListener('blur', mark);
    document.addEventListener('visibilitychange', mark);
    setTimeout(function () {
      window.removeEventListener('blur', mark);
      document.removeEventListener('visibilitychange', mark);
      if (handled) { return; }
      openPanel(addr);
    }, 1000);
  });
})();
</script>'''

PAGE_JS = '''<script>
(function () {
  var btn = document.getElementById('menu-btn');
  if (btn) {
    btn.addEventListener('click', function () {
      var open = document.body.classList.toggle('menu-open');
      btn.setAttribute('aria-expanded', open ? 'true' : 'false');
    });
    document.querySelectorAll('#links a').forEach(function (a) { a.addEventListener('click', function () { document.body.classList.remove('menu-open'); btn.setAttribute('aria-expanded', 'false'); }); });
  }
  var cols = document.querySelectorAll('.cols .col');
  cols.forEach(function (c) {
    c.addEventListener('mouseenter', function () { cols.forEach(function (o) { o.classList.toggle('open', o === c); }); });
    c.addEventListener('focusin', function () { cols.forEach(function (o) { o.classList.toggle('open', o === c); }); });
  });

  /* Scroll reveal. The observer is the primary path; the sweep below is the guarantee
     that nothing in view is ever left at opacity 0, whatever happens to the observer. */
  var pending = Array.prototype.slice.call(document.querySelectorAll('.reveal'));
  var observerRan = false;
  function show(el) { el.classList.add('in'); }
  function inView(el) {
    var r = el.getBoundingClientRect();
    var vh = window.innerHeight || document.documentElement.clientHeight;
    return r.top < vh * 0.96 && r.bottom > 0;
  }
  function sweep() {
    pending = pending.filter(function (el) {
      if (el.classList.contains('in')) { return false; }
      if (inView(el)) { show(el); return false; }
      return true;
    });
    if (!pending.length) {
      window.removeEventListener('scroll', sweep);
      window.removeEventListener('resize', sweep);
    }
  }
  if ('IntersectionObserver' in window) {
    var io = new IntersectionObserver(function (entries) {
      observerRan = true;
      entries.forEach(function (en) { if (en.isIntersecting) { show(en.target); io.unobserve(en.target); } });
    }, { rootMargin: '0px 0px -8% 0px', threshold: 0.08 });
    pending.forEach(function (el) { io.observe(el); });
  } else {
    pending.forEach(show);
    pending = [];
  }
  setTimeout(sweep, 900);
  window.addEventListener('load', function () { setTimeout(sweep, 300); });
  setTimeout(function () {
    if (observerRan) { return; }
    sweep();
    window.addEventListener('scroll', sweep, { passive: true });
    window.addEventListener('resize', sweep);
  }, 1800);
})();
</script>'''


# A GA4 event for every tap on a tel: link (Ron's SEO brief, 2026-09-29, P0.3): click_phone with where the link
# sits (its data-loc: header, footer, cta) and the page path. It only calls the gtag() the standard snippet in
# <head> defines; the GA tag itself is untouched. The museum pages carry the same script (museum/tools/build_artist_pages.py).
CALL_JS = '''<script>
document.addEventListener('click', function (e) {
  var a = e.target && e.target.closest ? e.target.closest('a[href^="tel:"]') : null;
  if (!a || typeof window.gtag !== 'function') { return; }
  window.gtag('event', 'click_phone', { link_location: a.getAttribute('data-loc') || 'page', page_path: location.pathname });
});
</script>'''
PAGE_JS = PAGE_JS + '\n' + CALL_JS

# The buyer pages' line under the wordmark (nav(sub=...), Ron, 2026-09-29): hidden on the first fold, shown from
# the second room of the opening on, gone once the black intro block (#intro) enters the viewport. Scroll position
# only, so the static fallback (no WebGL, reduced motion) behaves the same. Absent element: nothing runs.
WM_SUB_JS = '''<script>
(function () {
  var sub = document.querySelector('.nav .wm-sub'), intro = document.getElementById('intro');
  if (!sub || !intro) { return; }
  var queued = false;
  function update() {
    queued = false;
    var vh = window.innerHeight;
    sub.classList.toggle('on', window.scrollY > vh * 0.6 && intro.getBoundingClientRect().top > vh * 0.85);
  }
  function queue() { if (!queued) { queued = true; requestAnimationFrame(update); } }
  window.addEventListener('scroll', queue, { passive: true });
  window.addEventListener('resize', queue);
  window.addEventListener('load', update);
  update();
})();
</script>'''

# The same line on a growth page with a text hero (nav(sub=...) from the page JSON's nav_sub_en and nav_sub_he;
# /for-designers/, Ron, 2026-09-29): hidden on the first fold, shown once the page's h1 has scrolled fully out of
# view, and kept for the rest of the page (there is no black intro block here to hide it at).
WM_SUB_H1_JS = '''<script>
(function () {
  var sub = document.querySelector('.nav .wm-sub'), h1 = document.querySelector('.phead h1') || document.querySelector('h1');
  if (!sub || !h1) { return; }
  var queued = false;
  function update() {
    queued = false;
    sub.classList.toggle('on', h1.getBoundingClientRect().bottom < 0);
  }
  function queue() { if (!queued) { queued = true; requestAnimationFrame(update); } }
  window.addEventListener('scroll', queue, { passive: true });
  window.addEventListener('resize', queue);
  window.addEventListener('load', update);
  update();
})();
</script>'''


def body_open():
    """English is set in the markup itself; LANG_BOOT only switches to a stored choice."""
    return '<body class="lang-en">\n\n' + LANG_BOOT + '\n\n'


def tail(home=False, scripts=''):
    """scripts: extra script tags a page needs (BA_SCRIPT on the pages with a before/after figure)."""
    extra = '\n' + scripts if scripts else ''
    return '\n' + footer(home) + '\n\n' + MAIL_UI + '\n' + LANG_JS + '\n' + PAGE_JS + extra + '\n\n</body>\n</html>\n'


def redirect_stub(target, title='THEODORA', noindex=True):
    """A page that moved: canonical and meta refresh to its new address, a location.replace
    for browsers (no history entry, fragments included), noindex. Used for the retired /2/
    tree and the old Squarespace paths (/our-team/, /our-team-1/, /questions/).
    noindex=False: a page merged into another (/designers/ into /for-designers/, Ron's SEO brief of 2026-09-29, P1.5),
    where the instant refresh should read as a permanent redirect and pass the old page's signals on."""
    robots = '\n<meta name="robots" content="noindex">' if noindex else ''
    return f'''<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{H.escape(title)}</title>
<link rel="canonical" href="{target}">
<meta http-equiv="refresh" content="0; url={target}">{robots}
<script>location.replace({json.dumps(target)});</script>
</head>
<body>
<p>This page has moved. Continue to <a href="{target}">{target}</a>.</p>
<p lang="he" dir="rtl">העמוד הזה עבר. המשיכו אל <a href="{target}">{target}</a>.</p>
</body>
</html>
'''


# ---------------------------------------------------------------- posts
PAIR_RE = re.compile(
    r'<script type="application/ld\+json">\s*(.*?)\s*</script>\s*'
    r'<article class="(post[^"]*)" id="([a-z0-9\-]+)">(.*?)</article>',
    re.S,
)


def read_posts(path=POSTS_FILE):
    """content/posts.html as text, and one dict per post, newest first (file order)."""
    src = open(path, encoding='utf-8', newline='').read()
    pairs = PAIR_RE.findall(src)
    if not pairs:
        raise SystemExit('No posts found in content/posts.html: check the JSON-LD <script> + <article class="post" id="slug"> structure.')
    posts = []
    for json_text, article_class, slug, inner in pairs:
        data = json.loads(json_text)

        def grab(rx):
            mm = re.search(rx, inner, flags=re.S)
            return strip_tags(mm.group(1)) if mm else ''
        date_en = grab(r'<div class="post-date" data-l="en">(.*?)</div>')
        date_he = grab(r'<div class="post-date" data-l="he"[^>]*>(.*?)</div>')
        title_en = title_he = ''
        for attrs, t in re.findall(r'<h2 class="post-title[^"]*"([^>]*)>(.*?)</h2>', inner, flags=re.S):
            tag = attrs + ' '
            if 'post-title-he' in tag or 'data-l="he"' in tag or 'dir="rtl"' in tag:
                title_he = title_he or strip_tags(t)
            else:
                title_en = title_en or strip_tags(t)
        m_en = re.search(r'<h2 class="post-title post-title-en"[^>]*>(.*?)</h2>', inner, flags=re.S)
        m_he = re.search(r'<h2 class="post-title post-title-he"[^>]*>(.*?)</h2>', inner, flags=re.S)
        if m_en:
            title_en = strip_tags(m_en.group(1))
        if m_he:
            title_he = strip_tags(m_he.group(1))
        en_body = re.search(r'<div class="post-body post-body-en"[^>]*>(.*?)$', inner, flags=re.S)
        he_body = re.search(r'<div class="post-body" lang="he"[^>]*>(.*?)<div class="post-body post-body-en"', inner, flags=re.S)
        p_en = re.search(r'<p[^>]*>(.*?)</p>', en_body.group(1), flags=re.S) if en_body else None
        p_he = re.search(r'<p[^>]*>(.*?)</p>', he_body.group(1), flags=re.S) if he_body else None
        img = re.search(r'<img[^>]+src="([^"]+)"', inner)
        img_src = img.group(1) if img else ''
        if img_src and not img_src.startswith('/'):
            img_src = '/' + img_src
        assert date_en and date_he and title_en and title_he, f'post {slug}: date or title twin missing'
        posts.append(dict(
            slug=slug, article_class=article_class, json_text=json_text, article_inner=inner,
            headline=data['headline'], description=data['description'],
            datePublished=data['datePublished'], dateModified=data.get('dateModified', data['datePublished']),
            date_en=date_en, date_he=date_he, title_en=title_en, title_he=title_he,
            teaser_en=first_sentence(p_en.group(1)) if p_en else '',
            teaser_he=first_sentence(p_he.group(1)) if p_he else '',
            img=img_src,
            og_image=(SITE + img_src) if img_src else (SITE + '/og-image.jpg'),
        ))
    return src, posts


def month_labels(post):
    m = re.match(r'([A-Za-z]+) \d+, (\d{4})', post['date_en'])
    en = f'{m.group(1)} {m.group(2)}' if m else post['date_en']
    mh = re.match(r'\d+ ב(.+)$', post['date_he'])
    he = mh.group(1) if mh else post['date_he']
    return en, he


def timeline(posts, with_months):
    """The posts as timeline entries (the homepage, /radar/, and the More list on a post)."""
    out = []
    last = None
    for p in posts:
        mon = month_labels(p)
        if with_months and mon != last:
            out.append(f'<div class="month"><p class="eyebrow">{T(mon[0], mon[1])}</p></div>')
            last = mon
        th = f'<div class="th"><img src="{p["img"]}" alt="" loading="lazy"></div>' if p['img'] else '<div class="th"></div>'
        teaser = f'<p class="teaser">{T(H.escape(p["teaser_en"]), H.escape(p["teaser_he"]))}</p>' if p['teaser_en'] else ''
        out.append(f'''
      <a class="entry reveal" href="/radar/{p['slug']}/">
        <div class="date">{T(p['date_en'], p['date_he'])}</div>
        <div><h3 class="serif">{T(H.escape(p['title_en']), H.escape(p['title_he']))}</h3>{teaser}</div>
        {th}
      </a>''')
    return ''.join(out)


def project_card(p):
    """One project card, the same markup on the homepage, the hubs and the project pages.
    A project with no clean photograph of its own (2026-09-28: the Gemini-marked photos were removed)
    gets a quiet typographic panel with its place name, never a photo borrowed from another project."""
    hero = p.get('hero_image')
    if hero:
        ph = f'<div class="ph"><img src="{hero["src"]}" {img_alt(hero.get("alt_en", ""), hero.get("alt_he", ""))} loading="lazy"></div>'
    else:
        ph = f'<div class="ph type" aria-hidden="true">{T(H.escape(p["place_en"]), H.escape(p["place_he"]), cls="serif")}</div>'
    return f'''
      <a class="card reveal" href="/{p['path'].strip('/')}/">
        {ph}
        <h3 class="serif">{T(H.escape(p['title_en']), H.escape(p['title_he']))}</h3>
        <p class="muted">{T(H.escape(first_sentence(p['lead_en'])), H.escape(first_sentence(p['lead_he'])))}</p>
      </a>'''


# ---------------------------------------------------------------- before and after
# The proposal spaces (2026-09-28): AI-rendered spaces with real catalog artworks composited onto the wall,
# pixel-aligned pairs in images/spaces/<key>_{before,after}.webp (1800 px, plus a 1000 px twin) described in
# content/spaces.json. Every one is labeled a proposal. With JavaScript and motion allowed, the figure pins
# while the reader scrolls and js/before-after.js brushes the after over the before (css/theme.css, .ba);
# without either, the same markup is a still pair, side by side on a wide screen and stacked on a phone.
BA_SCRIPT = '<script src="/js/before-after.js?v=20260928" defer></script>'
BA_LABEL = ('Proposal · how THEODORA would dress this space', 'הצעה · כך THEODORA הייתה מלבישה את החלל הזה')
BA_BEFORE_ALT = ('The same space before the proposal, its wall still bare.', 'אותו חלל לפני ההצעה, הקיר עדיין ריק.')
BA_SIZES = '(max-width: 767px) 100vw, min(1100px, 92vw)'
_spaces = None


def spaces():
    global _spaces
    if _spaces is None:
        _spaces = json.load(open(SPACES_FILE, encoding='utf-8'))['spaces']
    return _spaces


def space_src(key, side):
    return f'/images/spaces/{key}_{side}.webp'


def space_srcset(key, side):
    return f'/images/spaces/{key}_{side}-1000.webp 1000w, /images/spaces/{key}_{side}.webp 1800w'


def space_og(key):
    return f'/images/spaces/{key}_og.jpg'


def ba_preload(key):
    """The first pair's before, fetched early: it is the hero the reader sees first."""
    return (f'<link rel="preload" as="image" href="{space_src(key, "before")}" imagesrcset="{space_srcset(key, "before")}" '
            f'imagesizes="{BA_SIZES}" type="image/webp" fetchpriority="high">\n')


def before_after(key, first=False):
    """One before/after figure. first: the page's hero (the before loads eagerly, high priority)."""
    s = spaces()[key]
    w, h = s['w'], s['h']
    eager = 'loading="eager" fetchpriority="high"' if first else 'loading="lazy"'
    # data-art: the artwork's left and right edges and the focal point, as fractions of the image width, and the
    # image size: the brush crosses only the wall around the artwork, the one place the two images differ
    art = f"{s['art_x'][0]} {s['art_x'][1]} {s['fx']} {w} {h}"
    return f'''<figure class="ba" data-art="{art}" style="--fx:{s['fx'] * 100:.1f}%;--fy:{s['fy'] * 100:.1f}%;--ar:{w}/{h}">
    <div class="ba-pin">
      <div class="ba-stage">
        <div class="ba-pane ba-before">
          <img src="{space_src(key, 'before')}" srcset="{space_srcset(key, 'before')}" sizes="{BA_SIZES}" width="{w}" height="{h}" {img_alt(*BA_BEFORE_ALT)} {eager} decoding="async">
          <span class="ba-chip">{T('Before', 'לפני')}</span>
        </div>
        <div class="ba-pane ba-after">
          <div class="ba-wipe"><img src="{space_src(key, 'after')}" srcset="{space_srcset(key, 'after')}" sizes="{BA_SIZES}" width="{w}" height="{h}" {img_alt(s['alt_en'], s.get('alt_he', ''))} loading="lazy" decoding="async"></div>
          <span class="ba-chip">{T('After', 'אחרי')}</span>
        </div>
      </div>
      <figcaption><span class="ba-label">{T(*BA_LABEL)}</span> {T(H.escape(s['cap_en']), H.escape(s['cap_he']))}</figcaption>
    </div>
  </figure>'''


# ---------------------------------------------------------------- the dash sanitizer
# No em dash (U+2014) and no en dash (U+2013) in anything a page says: visible text, titles, meta content, alt and
# aria-label text, JSON-LD strings, and the entity spellings of both (Ron's SEO brief, 2026-09-29, P0.2). One step
# every generator runs: write() below (build-site-pages.py, build-post-pages.py, build-home.py) and
# museum/tools/build_artist_pages.py. href, src and srcset values are never touched. The rules, in order:
#   1. a number range ("1571-1610" written with a dash, "27 BCE-130 CE", "19th-16th", "April 10-May 11") reads "to"
#   2. a spaced dash used as a break becomes a comma
#   3. an unspaced en dash joining two words (Wikipedia's "Greek-English Lexicon") becomes a hyphen
#   4. any other dash becomes a comma; doubled commas and commas before a stop are cleaned up
# Where a replacement reads badly, fix the source (the Art Radar posts in content/posts.html are fixed by hand).
DASH_ENTITY = re.compile(r'&(?:(m)dash|ndash|#(8212)|#8211|#x(2014)|#x2013);', re.I)
DASH_ANY = re.compile(r'[\u2013\u2014]|&(?:mdash|ndash|#8212|#8211|#x2014|#x2013);', re.I)
_MONTHS = ('January|February|March|April|May|June|July|August|September|October|November|December|'
           'Jan|Feb|Mar|Apr|Jun|Jul|Aug|Sept|Sep|Oct|Nov|Dec')
_RANGE = re.compile(r'(\d(?:st|nd|rd|th|s)?(?:\s?(?:BCE|BC|CE|AD)\b)?)\s*[\u2013\u2014]\s*(?=\d|c\.\s?\d|(?:' + _MONTHS + r')\b)')
_BREAK = re.compile(r'\s+[\u2013\u2014]\s+')
_JOIN = re.compile(r'(?<=[^\W\d_])\u2013(?=[^\W\d_])')
_REST = re.compile(r'\s*[\u2013\u2014]\s*')
COPY_ATTRS = re.compile(r'(\s(?:title|content|alt|data-alt-he|aria-label|placeholder|label)=")([^"]*)(")')
_TOKENS = re.compile(r'(<script\b[^>]*>.*?</script\s*>|<style\b.*?</style\s*>|<!--.*?-->|<[^>]+>)', re.S | re.I)
_JSON_STR = re.compile(r'"(?:[^"\\]|\\.)*"')
_URLISH = re.compile(r'^(?:https?:|mailto:|tel:|/|#)')


def undash(s, trailing=False):
    """One piece of copy without em or en dashes. trailing: a JSON-LD string may end on a dash (a cut
    description); drop it there instead of leaving a comma."""
    if not s or not DASH_ANY.search(s):
        return s
    s = DASH_ENTITY.sub(lambda m: '\u2014' if (m.group(1) or m.group(2) or m.group(3)) else '\u2013', s)
    if trailing:
        s = re.sub(r'\s*[\u2013\u2014]\s*$', '', s)
    s = _RANGE.sub(r'\1 to ', s)
    s = _BREAK.sub(', ', s)
    s = _JOIN.sub('-', s)
    s = _REST.sub(', ', s)
    s = re.sub(r',(\s*,)+', ',', s)
    s = re.sub(r',\s*([.;:!?)\]])', r'\1', s)
    s = re.sub(r'([(\[])\s*,\s*', r'\1', s)
    return s


def _undash_json(block):
    """The JSON-LD inside a <script type="application/ld+json">: every string value that is not a URL, the
    formatting kept byte for byte around it."""
    def one(m):
        lit = m.group(0)
        if not DASH_ANY.search(lit) and '\\u201' not in lit:
            return lit
        val = json.loads(lit)
        if _URLISH.match(val):
            return lit
        new = undash(val, trailing=True)
        return lit if new == val else json.dumps(new, ensure_ascii=False)
    return _JSON_STR.sub(one, block)


def undash_html(page):
    """A whole page through the sanitizer: text nodes, copy attributes and JSON-LD; other scripts, styles,
    comments, href, src and srcset stay as they are."""
    out = []
    for i, part in enumerate(_TOKENS.split(page)):
        if i % 2 == 0:
            out.append(undash(part))
        elif part[:7].lower() == '<script':
            if 'application/ld+json' in part[:60]:
                head_end = part.index('>') + 1
                tail_start = part.lower().rindex('</script')
                part = part[:head_end] + _undash_json(part[head_end:tail_start]) + part[tail_start:]
            out.append(part)
        elif part[:6].lower() == '<style' or part.startswith('<!--'):
            out.append(part)
        else:
            out.append(COPY_ATTRS.sub(lambda m: m.group(1) + undash(m.group(2)) + m.group(3), part))
    return ''.join(out)


def dash_leftovers(page):
    """What the QA script (qa_theodora.py) would still count: every dash outside href, src and srcset values."""
    scrub = re.sub(r'(href|src|srcset)="[^"]*"', '', page)
    return [scrub[max(0, m.start() - 50):m.end() + 30] for m in DASH_ANY.finditer(scrub)]


def write(path, text):
    """Every generated page goes out through here: CRLF normalized, dashes sanitized, and the build stops
    if a dash is still left (hard rule, Ron's SEO brief of 2026-09-29)."""
    text = undash_html(text.replace('\r\n', '\n'))
    left = dash_leftovers(text)
    if left:
        raise SystemExit(f'{path} NOT written: {len(left)} em or en dash(es) the sanitizer could not place, '
                         f'fix the source: {left[:3]!r}')
    full = rel(path)
    os.makedirs(os.path.dirname(full), exist_ok=True)
    open(full, 'w', encoding='utf-8', newline='\n').write(text)
    return full
