#!/usr/bin/env python3
"""The chrome every generated page of stavtheodor.com shares.

One nav, one footer, one language switch, one mailto fallback panel, one GA tag, one
<head> builder, and the readers for the site's data files:

  content/posts.html   every Art Radar post (JSON-LD + <article> pairs, newest first)
  content/faq.json     the seven homepage questions (visible FAQ and FAQPage schema come from it)
  content/entity.json  the Person + ProfessionalService + WebSite graph

The generators import this module: build-home.py (index.html, the /2/ redirect stubs),
build-post-pages.py (radar/<slug>/, radar/, sitemap.xml) and build-site-pages.py
(advisory, projects, partners, guide). The theme itself is css/theme.css.

Rules honored everywhere: every visible string has an English and a Hebrew twin behind
the global switch (localStorage radarLang); every page opens in English unless the
visitor chose Hebrew (site owner's decision, 2026-09-26), so <body class="lang-en"> is in
the markup and no hreflang tags are emitted; the mailto fallback ships on every page; no
phone numbers; no em or en dashes in English.
"""
import html as H
import json
import os
import re

ROOT = os.path.dirname(os.path.abspath(__file__))
SITE = 'https://stavtheodor.com'
GA_ID = 'G-4300MN0Q97'
EMAIL = 'stav@stavtheodor.com'
WHATSAPP = 'https://chat.whatsapp.com/CapF9HczSoL4szwUKKtkq5'
INSTAGRAM = 'https://www.instagram.com/theodorafineart/'
POSTS_FILE = os.path.join(ROOT, 'content', 'posts.html')
FAQ_FILE = os.path.join(ROOT, 'content', 'faq.json')
ENTITY_FILE = os.path.join(ROOT, 'content', 'entity.json')
THEME_CSS = '/css/theme.css'


def rel(*parts):
    return os.path.join(ROOT, *parts)


# ---------------------------------------------------------------- guards
def guard_index():
    """index.html is generated by build-home.py. A post pasted into it by hand would be
    wiped by the next build, so every build refuses to run while one is there."""
    p = rel('index.html')
    if os.path.exists(p) and '<article class="post' in open(p, encoding='utf-8').read():
        raise SystemExit(
            'STOP: index.html contains an Art Radar <article class="post ...">.\n'
            'Posts live in content/posts.html (see ADD-BLOG-POST-GUIDE.md). index.html is generated.\n'
            'Move the post block (its JSON-LD <script> + <article>) to the top of content/posts.html,\n'
            'restore index.html (git checkout index.html), then run python3 build.py again. Nothing was written.'
        )


# ---------------------------------------------------------------- small helpers
def strip_tags(s):
    return H.unescape(re.sub(r'\s+', ' ', re.sub(r'<[^>]+>', '', s or ''))).strip()


def first_sentence(s):
    s = strip_tags(s)
    m = re.match(r'(.+?[.!?])(\s|$)', s)
    return (m.group(1) if m else s).strip()


def T(en, he, tag='span', cls=''):
    """An English and a Hebrew twin. The site's switch shows one of them."""
    c = f' class="{cls}"' if cls else ''
    return f'<{tag}{c} data-l="en">{en}</{tag}><{tag}{c} data-l="he" dir="rtl">{he}</{tag}>'


# ---------------------------------------------------------------- head pieces
FAVICONS = '''<link rel="icon" type="image/svg+xml" href="/favicon.svg">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32.png">
<link rel="apple-touch-icon" href="/apple-touch-icon.png">'''

FONTS = '''<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=DM+Serif+Display:ital@0;1&family=Plus+Jakarta+Sans:wght@400;500;600&family=Frank+Ruhl+Libre:wght@300;400;500&display=swap" rel="stylesheet">'''

GA_SNIPPET = f'''<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id={GA_ID}"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){{dataLayer.push(arguments);}}
  gtag('js', new Date());
  gtag('config', '{GA_ID}');
</script>'''

_entity_cache = None


def entity_graph():
    """The Person + ProfessionalService + WebSite graph, from content/entity.json."""
    global _entity_cache
    if _entity_cache is None:
        data = json.load(open(ENTITY_FILE, encoding='utf-8'))
        _entity_cache = ('<!-- Structured data: Person + Organization + WebSite (JSON-LD) -->\n'
                         '<script type="application/ld+json">\n'
                         + json.dumps(data, ensure_ascii=False, indent=2)
                         + '\n</script>')
    return _entity_cache


def load_faq():
    faq = json.load(open(FAQ_FILE, encoding='utf-8'))
    for q in faq:
        for k in ('q_en', 'a_en', 'q_he', 'a_he'):
            assert q.get(k), f'faq.json: item missing {k}'
    return faq


def faq_schema(faq):
    return {
        '@context': 'https://schema.org',
        '@type': 'FAQPage',
        'mainEntity': [{'@type': 'Question', 'name': q['q_en'],
                        'acceptedAnswer': {'@type': 'Answer', 'text': q['a_en']}} for q in faq],
    }


def faq_details(faq, first_open=True):
    """The visible questions, the same text as the FAQPage schema, word for word."""
    return ''.join(f'''
      <details class="qa"{' open' if (i == 0 and first_open) else ''}>
        <summary><h3 class="serif">{T(H.escape(q["q_en"]), H.escape(q["q_he"]))}</h3><span class="plus" aria-hidden="true"></span></summary>
        <p class="body">{T(H.escape(q["a_en"]), H.escape(q["a_he"]))}</p>
      </details>''' for i, q in enumerate(faq))


def ld_script(block):
    text = block if isinstance(block, str) else json.dumps(block, ensure_ascii=False, indent=2)
    return f'<script type="application/ld+json">\n{text}\n</script>'


def head(title, desc, url, og_image=None, og_type='website', lang='en', ld=(), noindex=False,
         og_title=None, og_desc=None, og_card_dims=False, og_image_alt=None, extra=''):
    """Everything from <!DOCTYPE> to </head>. Canonical, Open Graph, Twitter, favicons,
    fonts, the theme, the page's JSON-LD blocks, the entity graph and GA. No hreflang:
    both languages live at the same URL and English is the default, so the tags would
    only point every language at itself (dropped 2026-09-26)."""
    og_image = og_image or SITE + '/og-image.jpg'
    og_title = og_title or title
    og_desc = og_desc or desc
    dims = ''
    if og_card_dims:
        dims = '\n<meta property="og:image:width" content="1200">\n<meta property="og:image:height" content="630">'
    if og_image_alt:
        dims += f'\n<meta property="og:image:alt" content="{H.escape(og_image_alt, quote=True)}">'
    robots = '\n<meta name="robots" content="noindex">' if noindex else ''
    ld_html = ''.join(ld_script(b) + '\n' for b in ld)
    return f'''<!DOCTYPE html>
<html lang="{lang}" data-default-lang="{lang}">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover">
<title>{H.escape(title)}</title>{robots}
<meta name="description" content="{H.escape(desc, quote=True)}">
<meta property="og:title" content="{H.escape(og_title, quote=True)}">
<meta property="og:description" content="{H.escape(og_desc, quote=True)}">
<meta property="og:type" content="{og_type}">
<meta property="og:url" content="{url}">
<meta property="og:image" content="{og_image}">{dims}
<meta property="og:site_name" content="THEODORA">
<meta property="og:locale" content="en_US">
<meta property="og:locale:alternate" content="he_IL">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="{H.escape(og_title, quote=True)}">
<meta name="twitter:description" content="{H.escape(og_desc, quote=True)}">
<meta name="twitter:image" content="{og_image}">
<link rel="canonical" href="{url}">
{FAVICONS}
{FONTS}
<link rel="stylesheet" href="{THEME_CSS}">
{extra}{ld_html}{entity_graph()}

{GA_SNIPPET}
</head>
'''


# ---------------------------------------------------------------- body pieces
LANG_BOOT = '''<script>
/* Resolve the language before anything paints. English is the default on every page
   (it is already on <body> and <html> in the markup, so crawlers and no-JS readers get
   English without this script). A choice the visitor made on any page, stored as
   radarLang, wins everywhere. No browser-language guessing. */
(function () {
  document.documentElement.classList.add('js');
  var lang = 'en';
  try { var s = localStorage.getItem('radarLang'); if (s === 'he' || s === 'en') { lang = s; } } catch (e) {}
  document.body.classList.toggle('lang-en', lang === 'en');
  document.body.classList.toggle('lang-he', lang === 'he');
  document.documentElement.lang = lang;
})();
</script>'''

NAV_ITEMS = [
    ('#about', 'About', 'אודות'),
    ('/projects/', 'Projects', 'פרויקטים'),
    ('#advisory', 'Advisory', 'ייעוץ'),
    ('#museum', 'Museum', 'מוזיאון'),
    ('/radar/', 'Art Radar', 'ראדאר אמנות'),
    ('#faq', 'Questions', 'שאלות'),
    ('#contact', 'Contact', 'יצירת קשר'),
]
# Section links that have a page of their own: on the homepage they stay in-page, on every
# other page they go to that page instead of scrolling the homepage (2026-09-26).
SUBPAGE_FOR = {'#advisory': '/advisory/'}


def _link(href, home):
    """Section links stay in-page on the homepage. Elsewhere they go to their own page when
    one exists (Advisory), otherwise to the homepage section, except Contact: every page's
    footer carries id="contact"."""
    if href.startswith('#') and not home and href != '#contact':
        return SUBPAGE_FOR.get(href, '/' + href)
    return href


def nav(home=False):
    links = ''.join(f'<a href="{_link(h, home)}">{T(en, he)}</a>' for h, en, he in NAV_ITEMS)
    return f'''<nav class="nav" aria-label="Main">
  <a class="wordmark" href="{'#hero' if home else '/'}">THEODORA</a>
  <div class="right">
    <div class="links" id="links">{links}</div>
    <div class="lang-switch" role="group" aria-label="Choose language / בחירת שפה">
      <button type="button" data-lang="he" aria-pressed="false">עברית</button>
      <button type="button" data-lang="en" aria-pressed="false">English</button>
    </div>
    <button type="button" class="menu-btn" id="menu-btn" aria-controls="links" aria-expanded="false">{T('Menu', 'תפריט')}</button>
  </div>
</nav>'''


def footer(home=False):
    L = lambda h: _link(h, home)
    return f'''<footer class="foot" id="contact">
  <div class="left">
    <p class="eyebrow">{T('Contact', 'יצירת קשר')}</p>
    <h2 class="serif">{T('Send me one photo of the wall and a line about the space. I’ll tell you what I see.', 'שלחו לי תמונה אחת של הקיר ושורה על החלל. אספר לכם מה אני רואה.')}</h2>
    <a class="arrow" href="mailto:{EMAIL}"><span class="ln"></span>{T('Write to Stav', 'כתבו לסתיו')}</a>
    <a class="arrow" href="mailto:{EMAIL}" style="text-transform: none; letter-spacing: 0.02em;"><span class="ln"></span>{EMAIL}</a>
    <div class="wordmark" style="margin-top: 40px;">THEODORA</div>
    <p style="font-size: 15px; max-width: 560px;">{T('Stav Theodor-Kimhi, art curation and advisory. Tenafly, New Jersey, for New York, New Jersey and Tel Aviv.', "סתיו תאודור-קמחי, אוצרות וייעוץ אמנות. טנפליי, ניו ג'רזי, לניו יורק, ניו ג'רזי ולתל אביב.")}</p>
  </div>
  <div class="cols2">
    <div>
      <a href="/art-curator-new-jersey/">{T('Art curator in New Jersey', "אוצרת אמנות בניו ג'רזי")}</a><a href="/art-curator-new-york/">{T('Art curator in New York', 'אוצרת אמנות בניו יורק')}</a><a href="/advisory/">{T('Art advisory', 'ייעוץ אמנות')}</a><a href="/projects/">{T('Projects', 'פרויקטים')}</a><a href="/radar/">{T('Art Radar', 'ראדאר אמנות')}</a><a href="/museum/">{T('The Museum', 'המוזיאון')}</a><a href="{L('#faq')}">{T('Questions', 'שאלות')}</a><a href="/for-designers/">{T('Working with designers', 'עבודה עם מעצבים')}</a>
    </div>
    <div>
      <a href="{L('#about')}">{T('About', 'אודות')}</a><a href="{WHATSAPP}" target="_blank" rel="noopener">{T('Art Radar on WhatsApp', 'ראדאר אמנות בוואטסאפ')}</a><a href="{INSTAGRAM}" target="_blank" rel="noopener">{T('Instagram', 'אינסטגרם')}</a>
    </div>
    <p class="eyebrow copy">{T('Tenafly, New Jersey · © 2026 THEODORA', "טנפליי, ניו ג'רזי · © 2026 THEODORA")}</p>
  </div>
</footer>'''


MAIL_UI = f'''<div class="mail-fallback" id="mail-fallback" role="dialog" aria-modal="true" aria-labelledby="mail-fallback-title">
  <div class="card">
    <h3 id="mail-fallback-title" class="serif"><span data-l="en">Write to Stav</span><span data-l="he">כתבו לסתיו</span></h3>
    <p><span data-l="en">This browser has no email app set up, so nothing opened. Copy the address, or open it in your webmail.</span><span data-l="he">בדפדפן הזה לא מוגדרת תוכנת דואר, ולכן לא נפתח כלום. העתיקו את הכתובת, או פתחו אותה בדואר האינטרנטי שלכם.</span></p>
    <a class="addr" id="mail-fallback-addr" href="mailto:{EMAIL}">{EMAIL}</a>
    <div class="row">
      <button type="button" id="mail-fallback-copy"><span data-l="en">Copy</span><span data-l="he">העתקה</span></button>
      <a class="solid" id="mail-fallback-gmail" href="https://mail.google.com/mail/?view=cm&amp;fs=1&amp;to={EMAIL}" target="_blank" rel="noopener">Gmail</a>
      <a id="mail-fallback-outlook" href="https://outlook.live.com/mail/0/deeplink/compose?to={EMAIL}" target="_blank" rel="noopener">Outlook</a>
    </div>
    <button type="button" class="close"><span data-l="en">Close</span><span data-l="he">סגירה</span></button>
  </div>
</div>'''

LANG_JS = '''<script>
(function () {
  var KEY = 'radarLang';

  function apply(lang) {
    document.body.classList.toggle('lang-en', lang === 'en');
    document.body.classList.toggle('lang-he', lang === 'he');
    document.documentElement.lang = lang;
    document.querySelectorAll('.lang-switch button').forEach(function (b) {
      var on = b.getAttribute('data-lang') === lang;
      b.classList.toggle('active', on);
      b.setAttribute('aria-pressed', on ? 'true' : 'false');
    });
  }

  apply(document.body.classList.contains('lang-he') ? 'he' : 'en');

  document.querySelectorAll('.lang-switch button').forEach(function (b) {
    b.addEventListener('click', function () {
      var lang = b.getAttribute('data-lang');
      try { localStorage.setItem(KEY, lang); } catch (e) {}
      apply(lang);
    });
  });

  /* A mailto: link does nothing at all in a browser with no mail handler registered,
     which is why the Write to Stav button felt dead. Keep the mailto (it is correct
     and works on phones and with a real mail client), and if the click was swallowed,
     offer the address, a copy button and webmail compose links instead. */
  var panel = document.getElementById('mail-fallback');
  if (!panel) { return; }
  var addrEl = document.getElementById('mail-fallback-addr');
  var gmail = document.getElementById('mail-fallback-gmail');
  var outlook = document.getElementById('mail-fallback-outlook');
  var copyBtn = document.getElementById('mail-fallback-copy');

  function closePanel() { panel.classList.remove('open'); }

  function openPanel(addr) {
    addrEl.textContent = addr;
    addrEl.setAttribute('href', 'mailto:' + addr);
    gmail.setAttribute('href', 'https://mail.google.com/mail/?view=cm&fs=1&to=' + encodeURIComponent(addr));
    outlook.setAttribute('href', 'https://outlook.live.com/mail/0/deeplink/compose?to=' + encodeURIComponent(addr));
    panel.classList.add('open');
  }

  panel.addEventListener('click', function (e) {
    if (e.target === panel || e.target.classList.contains('close') || (e.target.parentNode && e.target.parentNode.classList && e.target.parentNode.classList.contains('close'))) {
      closePanel();
    }
  });
  document.addEventListener('keydown', function (e) {
    if (e.key === 'Escape') { closePanel(); }
  });
  copyBtn.addEventListener('click', function () {
    var addr = addrEl.textContent;
    var done = function () {
      var spans = copyBtn.querySelectorAll('span');
      var was = [];
      spans.forEach(function (s, i) { was[i] = s.textContent; });
      spans.forEach(function (s) { s.textContent = s.getAttribute('data-l') === 'he' ? 'הועתק' : 'Copied'; });
      setTimeout(function () { spans.forEach(function (s, i) { s.textContent = was[i]; }); }, 1600);
    };
    if (navigator.clipboard && navigator.clipboard.writeText) {
      navigator.clipboard.writeText(addr).then(done, function () {});
    } else {
      var t = document.createElement('textarea');
      t.value = addr; document.body.appendChild(t); t.select();
      try { document.execCommand('copy'); done(); } catch (e) {}
      document.body.removeChild(t);
    }
  });

  document.addEventListener('click', function (e) {
    var a = e.target && e.target.closest ? e.target.closest('a[href^="mailto:"]') : null;
    if (!a || a === addrEl) { return; }
    var addr = a.getAttribute('href').slice(7).split('?')[0];
    var handled = false;
    function mark() { handled = true; }
    window.addEventListener('blur', mark);
    document.addEventListener('visibilitychange', mark);
    setTimeout(function () {
      window.removeEventListener('blur', mark);
      document.removeEventListener('visibilitychange', mark);
      if (handled) { return; }
      openPanel(addr);
    }, 1000);
  });
})();
</script>'''

PAGE_JS = '''<script>
(function () {
  var btn = document.getElementById('menu-btn');
  if (btn) {
    btn.addEventListener('click', function () {
      var open = document.body.classList.toggle('menu-open');
      btn.setAttribute('aria-expanded', open ? 'true' : 'false');
    });
    document.querySelectorAll('#links a').forEach(function (a) { a.addEventListener('click', function () { document.body.classList.remove('menu-open'); btn.setAttribute('aria-expanded', 'false'); }); });
  }
  var cols = document.querySelectorAll('.cols .col');
  cols.forEach(function (c) {
    c.addEventListener('mouseenter', function () { cols.forEach(function (o) { o.classList.toggle('open', o === c); }); });
    c.addEventListener('focusin', function () { cols.forEach(function (o) { o.classList.toggle('open', o === c); }); });
  });

  /* Scroll reveal. The observer is the primary path; the sweep below is the guarantee
     that nothing in view is ever left at opacity 0, whatever happens to the observer. */
  var pending = Array.prototype.slice.call(document.querySelectorAll('.reveal'));
  var observerRan = false;
  function show(el) { el.classList.add('in'); }
  function inView(el) {
    var r = el.getBoundingClientRect();
    var vh = window.innerHeight || document.documentElement.clientHeight;
    return r.top < vh * 0.96 && r.bottom > 0;
  }
  function sweep() {
    pending = pending.filter(function (el) {
      if (el.classList.contains('in')) { return false; }
      if (inView(el)) { show(el); return false; }
      return true;
    });
    if (!pending.length) {
      window.removeEventListener('scroll', sweep);
      window.removeEventListener('resize', sweep);
    }
  }
  if ('IntersectionObserver' in window) {
    var io = new IntersectionObserver(function (entries) {
      observerRan = true;
      entries.forEach(function (en) { if (en.isIntersecting) { show(en.target); io.unobserve(en.target); } });
    }, { rootMargin: '0px 0px -8% 0px', threshold: 0.08 });
    pending.forEach(function (el) { io.observe(el); });
  } else {
    pending.forEach(show);
    pending = [];
  }
  setTimeout(sweep, 900);
  window.addEventListener('load', function () { setTimeout(sweep, 300); });
  setTimeout(function () {
    if (observerRan) { return; }
    sweep();
    window.addEventListener('scroll', sweep, { passive: true });
    window.addEventListener('resize', sweep);
  }, 1800);
})();
</script>'''


def body_open():
    """English is set in the markup itself; LANG_BOOT only switches to a stored choice."""
    return '<body class="lang-en">\n\n' + LANG_BOOT + '\n\n'


def tail(home=False):
    return '\n' + footer(home) + '\n\n' + MAIL_UI + '\n' + LANG_JS + '\n' + PAGE_JS + '\n\n</body>\n</html>\n'


def redirect_stub(target, title='THEODORA'):
    """A page that moved: canonical and meta refresh to its new address, a location.replace
    for browsers (no history entry, fragments included), noindex. Used for the retired /2/
    tree and the old Squarespace paths (/about/, /our-team/, /our-team-1/, /contact/, /questions/)."""
    return f'''<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{H.escape(title)}</title>
<link rel="canonical" href="{target}">
<meta http-equiv="refresh" content="0; url={target}">
<meta name="robots" content="noindex">
<script>location.replace({json.dumps(target)});</script>
</head>
<body>
<p>This page has moved. Continue to <a href="{target}">{target}</a>.</p>
<p lang="he" dir="rtl">העמוד הזה עבר. המשיכו אל <a href="{target}">{target}</a>.</p>
</body>
</html>
'''


# ---------------------------------------------------------------- posts
PAIR_RE = re.compile(
    r'<script type="application/ld\+json">\s*(.*?)\s*</script>\s*'
    r'<article class="(post[^"]*)" id="([a-z0-9\-]+)">(.*?)</article>',
    re.S,
)


def read_posts(path=POSTS_FILE):
    """content/posts.html as text, and one dict per post, newest first (file order)."""
    src = open(path, encoding='utf-8', newline='').read()
    pairs = PAIR_RE.findall(src)
    if not pairs:
        raise SystemExit('No posts found in content/posts.html: check the JSON-LD <script> + <article class="post" id="slug"> structure.')
    posts = []
    for json_text, article_class, slug, inner in pairs:
        data = json.loads(json_text)

        def grab(rx):
            mm = re.search(rx, inner, flags=re.S)
            return strip_tags(mm.group(1)) if mm else ''
        date_en = grab(r'<div class="post-date" data-l="en">(.*?)</div>')
        date_he = grab(r'<div class="post-date" data-l="he"[^>]*>(.*?)</div>')
        title_en = title_he = ''
        for attrs, t in re.findall(r'<h2 class="post-title[^"]*"([^>]*)>(.*?)</h2>', inner, flags=re.S):
            tag = attrs + ' '
            if 'post-title-he' in tag or 'data-l="he"' in tag or 'dir="rtl"' in tag:
                title_he = title_he or strip_tags(t)
            else:
                title_en = title_en or strip_tags(t)
        m_en = re.search(r'<h2 class="post-title post-title-en"[^>]*>(.*?)</h2>', inner, flags=re.S)
        m_he = re.search(r'<h2 class="post-title post-title-he"[^>]*>(.*?)</h2>', inner, flags=re.S)
        if m_en:
            title_en = strip_tags(m_en.group(1))
        if m_he:
            title_he = strip_tags(m_he.group(1))
        en_body = re.search(r'<div class="post-body post-body-en"[^>]*>(.*?)$', inner, flags=re.S)
        he_body = re.search(r'<div class="post-body" lang="he"[^>]*>(.*?)<div class="post-body post-body-en"', inner, flags=re.S)
        p_en = re.search(r'<p[^>]*>(.*?)</p>', en_body.group(1), flags=re.S) if en_body else None
        p_he = re.search(r'<p[^>]*>(.*?)</p>', he_body.group(1), flags=re.S) if he_body else None
        img = re.search(r'<img[^>]+src="([^"]+)"', inner)
        img_src = img.group(1) if img else ''
        if img_src and not img_src.startswith('/'):
            img_src = '/' + img_src
        assert date_en and date_he and title_en and title_he, f'post {slug}: date or title twin missing'
        posts.append(dict(
            slug=slug, article_class=article_class, json_text=json_text, article_inner=inner,
            headline=data['headline'], description=data['description'],
            datePublished=data['datePublished'], dateModified=data.get('dateModified', data['datePublished']),
            date_en=date_en, date_he=date_he, title_en=title_en, title_he=title_he,
            teaser_en=first_sentence(p_en.group(1)) if p_en else '',
            teaser_he=first_sentence(p_he.group(1)) if p_he else '',
            img=img_src,
            og_image=(SITE + img_src) if img_src else (SITE + '/og-image.jpg'),
        ))
    return src, posts


def month_labels(post):
    m = re.match(r'([A-Za-z]+) \d+, (\d{4})', post['date_en'])
    en = f'{m.group(1)} {m.group(2)}' if m else post['date_en']
    mh = re.match(r'\d+ ב(.+)$', post['date_he'])
    he = mh.group(1) if mh else post['date_he']
    return en, he


def timeline(posts, with_months):
    """The posts as timeline entries (the homepage, /radar/, and the More list on a post)."""
    out = []
    last = None
    for p in posts:
        mon = month_labels(p)
        if with_months and mon != last:
            out.append(f'<div class="month"><p class="eyebrow">{T(mon[0], mon[1])}</p></div>')
            last = mon
        th = f'<div class="th"><img src="{p["img"]}" alt="" loading="lazy"></div>' if p['img'] else '<div class="th"></div>'
        teaser = f'<p class="teaser">{T(H.escape(p["teaser_en"]), H.escape(p["teaser_he"]))}</p>' if p['teaser_en'] else ''
        out.append(f'''
      <a class="entry reveal" href="/radar/{p['slug']}/">
        <div class="date">{T(p['date_en'], p['date_he'])}</div>
        <div><h3 class="serif">{T(H.escape(p['title_en']), H.escape(p['title_he']))}</h3>{teaser}</div>
        {th}
      </a>''')
    return ''.join(out)


def project_card(p):
    """One project card, the same markup on the homepage, the hubs and the project pages."""
    hero = p['hero_image']
    return f'''
      <a class="card reveal" href="/{p['path'].strip('/')}/">
        <div class="ph"><img src="{hero['src']}" alt="{H.escape(hero.get('alt_en', ''), quote=True)}" loading="lazy"></div>
        <h3 class="serif">{T(H.escape(p['title_en']), H.escape(p['title_he']))}</h3>
        <p class="muted">{T(H.escape(first_sentence(p['lead_en'])), H.escape(first_sentence(p['lead_he'])))}</p>
      </a>'''


def write(path, text):
    full = rel(path)
    os.makedirs(os.path.dirname(full), exist_ok=True)
    open(full, 'w', encoding='utf-8', newline='\n').write(text.replace('\r\n', '\n'))
    return full
