#!/usr/bin/env python3
"""Idempotent: adds any growth page that llms.txt does not name yet, and appends the first
answers to answers.md if they are missing. Reads titles and descriptions from content/pages/*.json.
Run from repo root after build-site-pages.py.

Since 2026-09-26 this script no longer touches index.html: the homepage is generated by
build-home.py, and its Advisory rows and project cards come straight from content/pages.
Since 2026-10-01 it never rewrites a line of llms.txt (the summaries there are written by hand):
a page whose URL is missing gets one line at the end of its section, and nothing else changes.
It no longer touches agent.txt, a short fact sheet edited by hand."""
import glob, json, re, html as H
SITE = "https://stavtheodor.com"
pages = [json.load(open(f, encoding="utf-8")) for f in sorted(glob.glob("content/pages/*.json"))]
by = {p["path"].strip("/"): p for p in pages}
adv = [p for p in pages if p["section"] == "local"] + [p for p in pages if p["section"] == "advisory"]  # the two local landing pages first
prj = [p for p in pages if p["section"] == "projects"]
def t(path): return by[path]["title_en"] if path in by else None

# ---- llms.txt: add missing pages only, never rewrite a hand written line ----
s = open("llms.txt", encoding="utf-8").read()
extra = [p for p in pages if p["section"] in ("partners", "guide")]
def line(p): return f"- [{p['title_en']}]({SITE}/{p['path'].strip('/')}/): {p['meta_description']}"
def add_missing(s, heading, group):
    missing = [p for p in group if f"({SITE}/{p['path'].strip('/')}/)" not in s]
    if not missing:
        return s, 0
    m = re.search(rf"\n{re.escape(heading)}\n.*?(?=\n## |\Z)", s, flags=re.S)
    assert m, f"llms.txt has no {heading} section"
    block = m.group(0).rstrip("\n") + "\n" + "\n".join(line(p) for p in missing) + "\n"
    return s[:m.start()] + block + s[m.end():], len(missing)
s, n_adv = add_missing(s, "## Advisory pages", adv + extra)
s, n_prj = add_missing(s, "## Project pages", prj)
if n_adv or n_prj:
    open("llms.txt", "w", encoding="utf-8").write(s)

# ---- answers.md ----
s = open("answers.md", encoding="utf-8").read()
if "## What does an art advisor cost?" not in s:
    def ans(path, q):
        p = by.get(path)
        if not p: return ""
        lead = re.sub(r"<[^>]+>", "", p["lead_en"]).strip()
        return f"\n## {q}\n\n{lead} Full page, in English and Hebrew: {SITE}/{path}/\n"
    add = ans("advisory/what-does-an-art-advisor-cost", "What does an art advisor cost?") + \
          ans("advisory/how-the-art-advisory-process-works", "How does working with an art advisor work, step by step?") + \
          ans("advisory/art-for-a-new-build-in-bergen-county", "When should art come into a new house in Alpine, Tenafly or Closter, New Jersey?") + \
          ans("advisory/commissioning-art-for-a-new-home", "How do I commission an artwork made for my home?") + \
          ans("advisory/art-for-a-home-in-israel-from-abroad", "Can an art advisor in New York handle a home in Caesarea or Tel Aviv?")
    s = s.rstrip("\n") + "\n" + add
    open("answers.md", "w", encoding="utf-8").write(s)
print("llms.txt: added", n_adv, "advisory, partner or guide pages and", n_prj, "project pages")
